### ISSUE TITLE
Crawler deployment on k8s GPU tainted nodes

### ISSUE THREAD

**Issue by nadgowdas** [cloudviz/agentless-system-crawler#325]
## Description
In kubernetes/armada environment, gpu nodes are going to be `tainted` to restrict random pods being schedule on them. We need to add `toleration` annotation in the deployment manifest (pod specs) to enable crawler deployment on these `gpu tainted` nodes.

Currently armada cluster is using k8s v1.5.x, so we need to enable this annotation in the backward format. 
```
annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated","value":"gpu-task","effect":"NoSchedule"}]'
```

once the server version is upgraded to v1.6 we need to change it to new pod.spec format:
```
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "gpu-task"
        effect: "NoSchedule"
```
